#ifndef _NET_HTTPSTATUSCODE_H
#define _NET_HTTPSTATUSCODE_H

namespace net
{

enum HttpStatusCode
{
	HTTP_CONTINUE = 0x64,
	HTTP_SWITCHING_PROTOCOLS = 0x65,
	HTTP_OK = 0xC8,
	HTTP_CREATED = 0xC9,
	HTTP_ACCEPTED = 0xCA,
	HTTP_NON_AUTHORITATIVE_INFORMATION = 0xCB,
	HTTP_NO_CONTENT = 0xCC,
	HTTP_RESET_CONTENT = 0xCD,
	HTTP_PARTIAL_CONTENT = 0xCE,
	HTTP_MULTIPLE_CHOICES = 0x12C,
	HTTP_MOVED_PERMANENTLY = 0x12D,
	HTTP_FOUND = 0x12E,
	HTTP_SEE_OTHER = 0x12F,
	HTTP_NOT_MODIFIED = 0x130,
	HTTP_USE_PROXY = 0x131,
	HTTP_TEMPORARY_REDIRECT = 0x133,
	HTTP_BAD_REQUEST = 0x190,
	HTTP_UNAUTHORIZED = 0x191,
	HTTP_PAYMENT_REQUIRED = 0x192,
	HTTP_FORBIDDEN = 0x193,
	HTTP_NOT_FOUND = 0x194,
	HTTP_METHOD_NOT_ALLOWED = 0x195,
	HTTP_NOT_ACCEPTABLE = 0x196,
	HTTP_PROXY_AUTHENTICATION_REQUIRED = 0x197,
	HTTP_REQUEST_TIMEOUT = 0x198,
	HTTP_CONFLICT = 0x199,
	HTTP_GONE = 0x19A,
	HTTP_LENGTH_REQUIRED = 0x19B,
	HTTP_PRECONDITION_FAILED = 0x19C,
	HTTP_REQUEST_ENTITY_TOO_LARGE = 0x19D,
	HTTP_REQUEST_URI_TOO_LONG = 0x19E,
	HTTP_UNSUPPORTED_MEDIA_TYPE = 0x19F,
	HTTP_REQUESTED_RANGE_NOT_SATISFIABLE = 0x1A0,
	HTTP_EXPECTATION_FAILED = 0x1A1,
	HTTP_INTERNAL_SERVER_ERROR = 0x1F4,
	HTTP_NOT_IMPLEMENTED = 0x1F5,
	HTTP_BAD_GATEWAY = 0x1F6,
	HTTP_SERVICE_UNAVAILABLE = 0x1F7,
	HTTP_GATEWAY_TIMEOUT = 0x1F8,
	HTTP_HTTP_VERSION_NOT_SUPPORTED = 0x1F9
};

static const char* toString(HttpStatusCode code);

} // net


#endif // _NET_HTTPSTATUSCODE_H
