#add_subdirectory(ads) #New not in ABS410, just here for reference
add_subdirectory(audio)
add_subdirectory(apprater) #Apple only.
add_subdirectory(flurry)
add_subdirectory(framework)
add_subdirectory(game)
add_subdirectory(gr)
#add_subdirectory(hgr) #Why is this still here, I think Nibblers and ABC520 removed it, HGR is used in other projects...
add_subdirectory(img)
add_subdirectory(io)
add_subdirectory(lang)
add_subdirectory(lua)
add_subdirectory(math)
add_subdirectory(net)
#add_subdirectory(payment) Apple only.
add_subdirectory(pf)
add_subdirectory(util)