#add_subdirectory(ads)
add_subdirectory(audio)
#add_subdirectory(apprater)
add_subdirectory(flurry)
add_subdirectory(framework)
add_subdirectory(game)
add_subdirectory(gr)
#add_subdirectory(hgr) #Why is this still here, I think Nibblers and ABC520 removed it, HGR is used in other projects...
add_subdirectory(img)
add_subdirectory(io)
add_subdirectory(lang)
add_subdirectory(lua)
add_subdirectory(math)
add_subdirectory(net)
#add_subdirectory(payment)
add_subdirectory(pf)
add_subdirectory(util)